#!/usr/bin/env python3
import json
import os
import string


_TF_VARS_FILENAME="terraform.tfvars.json"
_PROJECTS_DIR='build/Builds'
_BUCKET_SUFFIX=".mucana.org"


def camel_to_kebab(name):
    tokens = []
    token_index = 0

    for l in name:
        if l in string.ascii_uppercase:
            tokens.append('')
            token_index += 1
        tokens[token_index-1] += l.lower()
    return '-'.join(tokens)


def run():
    projects = os.listdir(_PROJECTS_DIR)
    projects = [camel_to_kebab(p) for p in projects]
    buckets = [p + _BUCKET_SUFFIX for p in projects]
    cnames = {p: b for p, b in zip(projects, buckets)}
    with open(_TF_VARS_FILENAME, 'w') as f:
        f.write(json.dumps({"buckets": buckets, "cnames": cnames}))


if __name__=="__main__":
    run()
