#!/usr/bin/env python3
import argparse

from . import builds
from . import tf


def init():
    builds.ensure_cached()
    tf.gen_bucket_cname_vars(builds.as_list())
    tf.gen_bucket_policies(builds.as_list())


def sync():
    builds.sync()
    site.gen()
    site.sync()


if __name__=="__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--init", help="initializes local state to be ready to deploy.")
    parser.add_argument("--sync", help="uploads local build and site assets to mucana.org.")
    run()
